# Generated by Django 4.1.4 on 2023-03-10 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Write Description of this class (Who is the teacher? Who teacher going to teach and what subject etc...)', max_length=32)),
                ('time', models.TimeField()),
                ('cabinet', models.IntegerField()),
                ('description', models.CharField(max_length=300, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day', to='app.day')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('teacher', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_year', models.IntegerField()),
                ('group_title', models.CharField(max_length=10)),
                ('group_number', models.IntegerField()),
                ('lessons', models.ManyToManyField(blank=True, to='app.lesson')),
            ],
            options={
                'unique_together': {('group_year', 'group_title', 'group_number')},
            },
        ),
    ]
