# Generated by Django 4.1.4 on 2023-03-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='Write Description of this class (Who is the teacher? Who teacher going to teach and what subject etc...)', max_length=32),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='cabinet',
            field=models.IntegerField(),
        ),
    ]
