# Generated by Django 4.1.4 on 2023-03-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='group_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='group_year',
            field=models.IntegerField(),
        ),
    ]
