# Generated by Django 4.1.4 on 2023-03-10 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default= '')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day', to='app.daysofweek'),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
