# Generated by Django 4.1.4 on 2023-03-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_students_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='app.lesson'),
        ),
    ]
