# Generated by Django 4.1.4 on 2023-03-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_daysofweek_alter_lesson_title_alter_lesson_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
    ]
