# Generated by Django 4.1.4 on 2023-03-11 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_lesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysofweek',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='cabinet',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='day', to='app.daysofweek'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
